// Run with NODE_PATH pointing to a Playwright installation and preview on :5051.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const context = await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});
  const page = await context.newPage();
  async function navigate(name) {await page.locator('#menu-toggle').click();await page.locator(`[data-page=${name}]`).click();}
  const errors=[]; page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/scanner/api/session',route=>route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({error:'Απαιτείται σύνδεση'})}));
  await page.goto('http://127.0.0.1:5051/scanner/');
  await page.locator('#login-form').waitFor();
  await page.waitForFunction(()=>document.getElementById('network').textContent==='● Online');
  await page.route('**/scanner/api/connectivity?*',route=>route.abort());
  await page.evaluate(()=>checkConnectivity());
  assert.equal(await page.evaluate(()=>navigator.onLine),true);
  assert.equal(await page.locator('#network').textContent(),'○ Offline');
  await page.unroute('**/scanner/api/connectivity?*');
  await page.evaluate(()=>checkConnectivity());
  assert.equal(await page.locator('#network').textContent(),'● Online');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'work/scanner-login-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>typeof jsQR),'function');
  await page.evaluate(()=>navigator.serviceWorker.ready);
  await page.unroute('**/scanner/api/session');
  await page.route('**/scanner/api/session',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({stores:[{id:7,name:'Δοκιμαστικό κατάστημα',branch_aa:'2'}],store_id:7,owner:'fixture',pin_enabled:false,last_sync:'09/09/2026 10:30'})}));
  await page.route('**/scanner/api/login',route=>route.fulfill({contentType:'application/json',body:'{"success":true}'}));
  await page.route('**/scanner/api/recent?*',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({has_previous:false,has_next:false,events:[{id:'1in',name:'ΔΟΚΙΜΑΣΤΙΚΟΣ ΕΡΓΑΖΟΜΕΝΟΣ',employee_afm:'000000000',event:'in',date:'09/09/2026',time:'09:00',protocol:'ΕΞΩΤΕΡΙΚΗ-ΠΗΓΗ'},{id:'1out',name:'ΔΟΚΙΜΑΣΤΙΚΟΣ ΕΡΓΑΖΟΜΕΝΟΣ',employee_afm:'000000000',event:'out',date:'09/09/2026',time:'17:00',protocol:'ΠΡΩΤΟΚΟΛΛΟ-2'}]})}));
  await page.locator('[name=username]').fill('fixture');await page.locator('[name=password]').fill('fixture');await page.locator('#login-form button').click();
  await page.locator('#home').waitFor();
  assert.equal(await page.locator('#stores').count(),0);
  await page.locator('#sync-top').click();
  assert.equal(await page.locator('#sync-result').textContent(),'Δεν βρέθηκαν δηλώσεις προς υποβολή.');
  await page.locator('#sync-dialog button').click();
  await page.locator('#menu-toggle').click();
  assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'),'true');
  await page.screenshot({path:'work/scanner-menu-mobile.png',fullPage:true});
  await page.locator('#menu-close').click();await page.screenshot({path:'work/scanner-home-mobile.png',fullPage:true});
  assert.equal(await page.locator('[data-page=history]').count(),0);
  assert.equal(await page.locator('.brand img').getAttribute('src'),'/static/img/erganios-logo.png');
  assert.equal(await page.locator('#network').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)');
  await navigate('recent');await page.locator('#recent-list .event').first().waitFor();
  assert.equal(await page.locator('#recent-list .event').count(),2);
  await navigate('pending');
  assert.equal(await page.locator('#pending-count').textContent(),'0');
  await context.setOffline(true);
  await page.evaluate(async()=>{
    await storage('put',{request_id:'browser-test-0000000000000000',qr:'000000000',event:'in',event_at:new Date().toISOString(),name:'TEST ONLY',store_id:7,owner:'fixture',state:'pending',note:'Σε αναμονή σύνδεσης'});
    await renderPending();await sendPending();
  });
  assert.equal(await page.locator('#pending-count').textContent(),'1');
  assert.equal(await page.locator('#retry').isDisabled(),true);
  assert.equal(await page.locator('#network').textContent(),'○ Offline');
  await page.screenshot({path:'work/scanner-pending-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await navigate('settings');assert.equal(await page.locator('#settings').isVisible(),true);
  let submissions=0;
  await page.route('**/scanner/api/submit',route=>{submissions++;return route.fulfill({contentType:'application/json',body:'{"success":true,"persisted":true,"protocol":"TEST-ONLY"}'});});
  await page.evaluate(()=>document.getElementById('sound').checked=false);
  await context.setOffline(false);
  await page.waitForFunction(async()=>(await outbox())[0].state==='success');
  await page.waitForFunction(()=>document.getElementById('pending-count').textContent==='0');
  await page.evaluate(()=>sendPending());
  assert.equal(await page.locator('#pending-count').textContent(),'0');
  assert.equal(submissions,1);
  await page.evaluate(async()=>{await storage('put',{request_id:'manual-sync-0000000000000000',qr:'000000000',event:'in',event_at:new Date().toISOString(),name:'TEST ONLY',store_id:7,owner:'fixture',state:'pending'});await renderPending();});
  await page.locator('#sync-top').click();
  await page.waitForFunction(()=>document.getElementById('sync-result').textContent==='Υποβλήθηκαν επιτυχώς 1 δηλώσεις.');
  assert.equal(submissions,2);
  await page.locator('#sync-dialog button').click();
  assert.equal(await page.evaluate(async()=>(await outbox())[0].state),'success');
  await page.setViewportSize({width:1024,height:768});await navigate('home');await page.screenshot({path:'work/scanner-home-tablet.png',fullPage:true});
  await page.unroute('**/scanner/api/session');
  await page.route('**/scanner/api/session',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({stores:[{id:7,name:'Test',branch_aa:'2'}],store_id:7,owner:'fixture',pin_enabled:true})}));
  await page.evaluate(()=>{session.pin_enabled=true;});
  await navigate('pending');assert.equal(await page.locator('#unlock-dialog').isVisible(),false);
  await navigate('settings');assert.equal(await page.locator('#unlock-dialog').isVisible(),false);
  await navigate('recent');assert.equal(await page.locator('#unlock-dialog').isVisible(),true);
  await page.locator('#cancel-unlock').click();
  assert.deepEqual(errors,[]);await browser.close();console.log('Scanner browser smoke passed: mobile/tablet, assets, SW, navigation, pending offline/reconnect, recent punches.');
})().catch(error=>{console.error(error);process.exit(1);});
